version: '3.7'
services:

  web:
    build: './web'
    image: 'sose-web:0.0.1'
    ports:
      - "3000:3000"

  users:
    build: './users'
    image: 'sose-users:0.0.1'
    ports:
      - "3111:3000"
    depends_on: 
      - users-mongodb
    environment:
      - MONGO_DB_URI=mongodb://users-mongodb:27017
      - log_level=0

  users-mongodb:
    image: mongo:3.6.18-xenial
    volumes:
      - ./userdata:/data/db
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=users
    restart: on-failure

  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - users

volumes:
  userdata: