version: '3.7'
services:

  web:
    build: './web'
    image: 'sose-web:0.0.1'
    ports:
      - "3000:3000"

  users:
    build: './users'
    image: 'sose-users:0.0.1'
    ports:
      - "3111:3000"
    depends_on: 
      - users-mongodb
    environment:
      - MONGO_DB_URI=mongodb://user-mongodb:27111
      - log_level=0

  user-mongodb:
    image: mongo:3.6.18-xenial
    volumes:
      - ./users/userdata:/data/db
    command: mongod --port 27111 --quiet
    ports:
      - "27111:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      # - MONGO_INITDB_DATABASE=users

  movies:
    build: './movies'
    image: 'sose-movies:0.0.1'
    ports:
      - "3222:3000"
    depends_on: 
      - movie-mongodb
    environment:
      - MONGO_DB_URI=mongodb://movie-mongodb:27222
  
  movie-mongodb:
    image: mongo:3.6.18-xenial
    volumes:
      - ./movies/moviedata:/data/db
    command: mongod --port 27222 --quiet
    ports:
      - "27222:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      # - MONGO_INITDB_DATABASE=users

  reviews:
    build: './reviews'
    image: 'sose-reviews:0.0.1'
    ports:
        - "3333:3000"
    depends_on: 
        - review-mongodb
    environment:
      - MONGO_DB_URI=mongodb://review-mongodb:27333

  review-mongodb:
    image: mongo:3.6.18-xenial
    volumes:
        - ./reviews/reviewdata:/data/db
    command: mongod --port 27333 --quiet
    ports:
      - "27333:27017"
    # environment:
    #   # - MONGO_INITDB_ROOT_USERNAME=admin
    #   # - MONGO_INITDB_ROOT_PASSWORD=admin
    #   - MONGO_INITDB_DATABASE=users

  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - users
      - movies
      - reviews

volumes:
  userdata:
  moviedata:
  reviewdata:
